[tool.poetry]
name = "bulloh"
version = "0.1.0"
description = "Script to automate gathering personal productivity data."
readme = "README.md"
authors = ["anggelomos <anggelomos@outlook.com>"]
packages = [{include = "bulloh", from = "src"}]

[tool.poetry.urls]
repository = "https://github.com/anggelomos/bulloh"

[tool.poetry.dependencies]
python = "^3.10"
tickthon = ">=0.2.9"
cattrs = "*"
python-dotenv = ">=1.1.1,<2.0.0"
nothion = "^0.4.9"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
twine = "*"
flake8 = "*"
mypy = "*"
types-requests = "*"
boto3-stubs = {extras = ["essential"], version = "*"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"