# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on: [push, workflow_dispatch]

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  NT_AUTH: ${{ secrets.NT_AUTH }}
  NT_STATS_DB_ID: ${{ secrets.NT_STATS_DB_ID }}
  TT_USER: ${{ secrets.TT_USER }}
  TT_PASS: ${{ secrets.TT_PASS }}
  TICKTICK_IDS: ${{ secrets.TICKTICK_IDS }}
  RT_API_KEY: ${{ secrets.RT_API_KEY }}

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build wheel
        pip install -e .[dev]

    - name: Lint with flake8
      run: flake8 src

    - name: Lint with mypy
      run: mypy src

    - name: Test with pytest
      run: pytest --cov

    - name: Build package
      run: python -m build

  release:
      needs: build
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel

      - name: Increment minor version
        run: |
          pip install -U bulloh toml
          python .github/scripts/increment_version.py

      - name: Build package
        run: python -m build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  update-lambda:
    needs: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build awscli

      - name: Create lambda package
        run: |
          mkdir lambda-deployment-package
          cp -r src main.py lambda_function.py lambda-deployment-package
          pip install -t lambda-deployment-package .
          cd lambda-deployment-package
          zip -r ../lambda-deployment-package.zip .
          cd ..

      - name: Upload lambda package
        run: aws lambda update-function-code --function-name bulloh-runner --zip-file fileb://lambda-deployment-package.zip --region us-east-1